### ISSUE TITLE
tietar needs to be replaced

### ISSUE THREAD

**Issue by 153957** [HiSPARC/servers#1]
tietar is currently down, probably crashed (will try to boot on Monday).
The server has a hard time to keep up with all the traffic.
Nagios often using a lot of resources (CPU and RAM).
So much RAM that it needs to swap, slowing things down further.

If it is to be replaced by a new server we can try to use vagrant/ansible for setup.
And perhaps try the latest version of Nagios, or test a drop-in alternative like shinken (Python).

**Comment by davidfokkema** [comment]
That is bad news. If it boots up on Monday, first thing we should do is copy the keys in /etc/nagios. If we lose them, we need to pay every high school a visit...

**Comment by 153957** [comment]
Good point!

**Comment by 153957** [comment]
Probably bad power supply.

**Comment by 153957** [comment]
This was done.
